import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {Header} from '@/components/Header/Header'
import Footer  from '@/components/Footer/Footer'
import 'aos/dist/aos.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Traum Auto',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="relative">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
